apiVersion: v1
kind: Pod
metadata:
  name: helloworld-go
  labels:
    app: helloworld-go
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi! I'm an environment variable
    image: mcleary/helloworld-go
    imagePullPolicy: Always
    name: helloworld-override
    resources: {}