apiVersion: v1
kind: Pod
metadata:
  name: helloworld-2
  labels:
    app: helloworld-go
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi!. This should be a different message.
    image: mcleary/helloworld-go
    imagePullPolicy: Always
    name: helloworld-override
    resources: {}
